codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "90...100"

  status:
    project:
        default:
            threshold: 1%
    patch: yes
    changes: no

  ignore:
    - "src/Testing/**/*"
    - "src/Testing"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

