version: '3'

services:
    php:
        image: tenancy/tenancy-ci-php-${PHP_VERSION}:latest

        volumes:
            - '${TENANCY_PATH-../../}:/var/www/html'
            - '${TENANCY_PATH-../../}.dev/Docker/Partials/:/ops/'
            
        networks:
            - application

        depends_on:
            - mysql

        tty: true
        stdin_open: true

    mysql:
        image: tenancy/tenancy-ci-mysql-${DB_VERSION}:latest

        environment:
            MYSQL_DATABASE: testing
            MYSQL_USER: testing
            MYSQL_PASSWORD: testing
            MYSQL_ROOT_PASSWORD: password
            MYSQL_ALLOW_EMPTY_PASSWORD: ''
            MYSQL_ROOT_HOST: "%"

        command: --default-authentication-plugin=mysql_native_password

        ports:
            - 13306:3306
            
        networks:
            - application

networks:
    application:
        driver: bridge
