version: '3'

services:
    php:
        # build:
        #     context: ./Images/PHP/
        #     args:
        #         VERSION: ${PHP_VERSION}
        image: arlonwip/php:${PHP_VERSION}

        volumes:
            - '${TENANCY_PATH-../../}:/var/www/html'
            - '${TENANCY_PATH-../../}.dev/Docker/Partials/wait-for-it.sh:/ops/wait-for-it.sh'
            
        networks:
            - application

        depends_on:
            - mysql

        tty: true
        stdin_open: true

    mysql:
        # build:
        #     context: ./Images/MySQL/
        #     args:
        #         VERSION: ${DB_VERSION}
        image: arlonwip/mysql:${DB_VERSION}

        environment:
            MYSQL_DATABASE: testing
            MYSQL_USER: testing
            MYSQL_PASSWORD: testing
            MYSQL_ROOT_PASSWORD: password
            MYSQL_ALLOW_EMPTY_PASSWORD: ''
            MYSQL_ROOT_HOST: "%"

        command: --default-authentication-plugin=mysql_native_password

        ports:
            - 13306:3306
            
        networks:
            - application

networks:
    application:
        driver: bridge
