version: '3'

services:
  php:
    image: tenancy/tenancy-ci-php-${PHP_VERSION}:latest

    volumes:
      - '${TENANCY_PATH-../../}:/var/www/html'
      - '${TENANCY_PATH-../../}.dev/docker/partials/:/ops/'
    
    networks:
      - application

    depends_on:
      - mysql

    tty: true
    stdin_open: true

  mysql:
    image: mysql:8.0

    environment:
      MYSQL_DATABASE: testing
      MYSQL_USER: testing
      MYSQL_PASSWORD: testing
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: ''
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./default_users.sql:/docker-entrypoint-initdb.d/default_users.sql

    ports:
      - "13306:3306"
    
    networks:
      - application

networks:
  application:
    driver: bridge
