name: Tests

on:
  push:
    branches:
      - '*.x'
      - 'master'
  pull_request:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.2', '8.3', '8.4', '8.5' ]
        laravel: [ '11.*', '12.*', '13.*' ]
        phpunit: [ '11.*', '12.*', '13.*' ]
        service: [ '8' ]
        dependency-version: [ prefer-lowest, prefer-stable ]
        exclude:
          # PHP 8.5 does not support Laravel 11
          - php: '8.5'
            laravel: '11.*'
          
          # PHP 8.2 does not support Laravel 13
          - php: '8.2'
            laravel: '13.*'
          
          # PHP 8.3 does not support PHPUnit 13
          - php: '8.3'
            phpunit: '13.*'

          # Laravel 11 does not support PHPUnit 10 or PHPUnit 12 or PHPUnit 13
          - laravel: '11.*'
            phpunit: '11.*'
          - laravel: '11.*'
            phpunit: '12.*'
          - laravel: '11.*'
            phpunit: '13.*'

          # Laravel 12 does not support PHPUnit 12 or PHPUnit 13
          - laravel: '12.*'
            phpunit: '12.*'
          - laravel: '12.*'
            phpunit: '13.*'
          
          # Laravel 13 does not support PHPUnit 11
          - laravel: '13.*'
            phpunit: '11.*'

    name: 'Tests: PHP ${{ matrix.php }} / Laravel: ${{ matrix.laravel }} / ${{ matrix.dependency-version }}'
    
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v6

      - name: Run tests
        run: ./test --php ${{ matrix.php }} --laravel ${{ matrix.laravel }} --db ${{ matrix.service }} --dependencies ${{ matrix.dependency-version }} --phpunit ${{ matrix.phpunit }}

  installation-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.2', '8.3', '8.4', '8.5' ]
        laravel: [ '12.0', '13.0' ]
        exclude:            
          # PHP 8.2 does not support Laravel 13
          - php: '8.2'
            laravel: '13.0'

    name: 'Installation: PHP ${{ matrix.php }} / Laravel: ${{ matrix.laravel }}'

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v6
        with:
          path: ./package

      - name: Install Laravel
        run: docker run --rm -v ${PWD}:/app composer:latest composer create-project laravel/laravel:^${{ matrix.laravel }} application

      - name: Add the package as a path repository
        run: |
          docker run --rm -v ${PWD}:/app --workdir /app/application composer:latest composer config repositories.0 path ../package

      - name: Require the package
        run: |
          docker run --rm -v ${PWD}:/app --workdir /app/application composer:latest composer require tenancy/tenancy:dev-main
